import json
import time

import pytest
import httpx

from app.llm.cache import InMemoryLLMCache
from app.llm.gateway import LLMGateway
from app.llm.prompt_registry import PromptRegistry


def test_prompt_registry_loads_versioned_prompts():
    registry = PromptRegistry()

    assert registry.list_prompt_ids() == [
        "customer_insight_clustering_v1",
        "daily_ops_summary_v1",
        "marketing_draft_v1",
    ]
    prompt = registry.get("marketing_draft_v1")
    assert prompt.agent == "marketing"
    assert prompt.allowed_for_agents == ["marketing"]


def test_llm_gateway_generates_deterministic_marketing_copy():
    response = LLMGateway().generate_text(
        prompt_id="marketing_draft_v1",
        agent="marketing",
        input_data={"product_name": "Trail Runner", "offer": "10% off"},
    )

    assert response.provider == "stub"
    assert response.model == "deterministic-marketing-v1"
    assert response.cached is False
    assert "Trail Runner" in response.output
    assert "requires approval before send" in response.output


def test_llm_gateway_enforces_agent_prompt_permissions():
    gateway = LLMGateway()

    with pytest.raises(PermissionError):
        gateway.generate_text(
            prompt_id="daily_ops_summary_v1",
            agent="marketing",
            input_data={},
        )


def test_llm_gateway_generates_daily_ops_summary():
    response = LLMGateway().generate_text(
        prompt_id="daily_ops_summary_v1",
        agent="orchestrator",
        input_data={
            "inventory_alerts": [{}, {}],
            "pricing_recommendations": [{}],
            "marketing_drafts": [{}],
            "approvals_required": [{}],
            "actions_blocked": [{}],
        },
    )

    assert response.model == "deterministic-summary-v1"
    assert "2 inventory alerts" in response.output
    assert "1 pending approvals" in response.output


def test_llm_gateway_generates_customer_insight_clusters():
    response = LLMGateway().generate_text(
        prompt_id="customer_insight_clustering_v1",
        agent="customer_insight",
        input_data={
            "reviews": [
                {
                    "review_id": "REV-POWER",
                    "sku": "SKU-1002",
                    "rating": 2,
                    "title": "Power dies quickly",
                    "body": "The earbuds stop working after one short call.",
                }
            ],
            "returns": [
                {
                    "return_id": "RET-POWER",
                    "sku": "SKU-1002",
                    "reason": "quality_issue",
                    "notes": "Doesn't hold charge through the day.",
                }
            ],
        },
    )

    payload = json.loads(response.output)

    assert response.model == "deterministic-customer-insight-v1"
    assert payload["clusters"][0]["issue"] == "Battery drain"
    assert payload["clusters"][0]["severity"] == "high"


def test_llm_gateway_calls_litellm_proxy_with_openai_compatible_payload(tmp_path):
    prompt_dir = tmp_path / "prompts"
    prompt_dir.mkdir()
    (prompt_dir / "test_prompt.yaml").write_text(
        """
prompt_id: test_litellm_prompt_v1
agent: marketing
provider: litellm
model: gemini/gemini-1.5-flash
system_prompt: Generate campaign copy from JSON.
temperature: 0.2
max_tokens: 200
input_schema: TestInput.v1
output_schema: string
allowed_for_agents:
  - marketing
fallback: null
cache_policy:
  enabled: false
""",
        encoding="utf-8",
    )
    captured_payload = {}

    def handler(request: httpx.Request) -> httpx.Response:
        captured_payload.update(json.loads(request.content.decode("utf-8")))
        return httpx.Response(
            200,
            json={
                "choices": [
                    {
                        "message": {
                            "content": "Generated by LiteLLM proxy.",
                        }
                    }
                ],
                "usage": {
                    "prompt_tokens": 12,
                    "completion_tokens": 5,
                    "total_tokens": 17,
                },
            },
        )

    gateway = LLMGateway(
        prompt_registry=PromptRegistry(prompt_dir),
        http_client=httpx.Client(transport=httpx.MockTransport(handler)),
        provider_override="prompt",
    )

    response = gateway.generate_text(
        prompt_id="test_litellm_prompt_v1",
        agent="marketing",
        input_data={"sku": "SKU-1003"},
    )

    assert response.provider == "litellm"
    assert response.model == "gemini/gemini-1.5-flash"
    assert response.output == "Generated by LiteLLM proxy."
    assert response.usage["total_tokens"] == 17
    assert captured_payload["model"] == "gemini/gemini-1.5-flash"
    assert captured_payload["messages"][0]["role"] == "system"
    assert captured_payload["messages"][1]["role"] == "user"
    assert '"sku": "SKU-1003"' in captured_payload["messages"][1]["content"]


def test_llm_gateway_falls_back_when_litellm_proxy_rejects_request(tmp_path):
    prompt_dir = tmp_path / "prompts"
    prompt_dir.mkdir()
    (prompt_dir / "failing_prompt.yaml").write_text(
        """
prompt_id: marketing_draft_v1
agent: marketing
provider: litellm
model: gemini/gemini-1.5-flash
system_prompt: Generate campaign copy from JSON.
temperature: 0.2
max_tokens: 200
input_schema: TestInput.v1
output_schema: string
allowed_for_agents:
  - marketing
fallback:
  strategy: deterministic_stub
cache_policy:
  enabled: false
""",
        encoding="utf-8",
    )

    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(401, json={"error": {"message": "API key not valid"}})

    gateway = LLMGateway(
        prompt_registry=PromptRegistry(prompt_dir),
        http_client=httpx.Client(transport=httpx.MockTransport(handler)),
        provider_override="prompt",
    )

    response = gateway.generate_text(
        prompt_id="marketing_draft_v1",
        agent="marketing",
        input_data={"product_name": "Trail Runner", "offer": "10% off"},
    )

    assert response.provider == "stub"
    assert response.model == "gemini/gemini-1.5-flash"
    assert "Trail Runner" in response.output
    assert response.usage["fallback_provider"] == "litellm"


def test_llm_gateway_uses_cache_when_prompt_policy_enables_it(tmp_path):
    prompt_dir = tmp_path / "prompts"
    prompt_dir.mkdir()
    (prompt_dir / "cached_prompt.yaml").write_text(
        """
prompt_id: cached_prompt_v1
agent: marketing
provider: litellm
model: openai/gpt-4.1-mini
system_prompt: Generate cached copy.
temperature: 0.0
max_tokens: 50
input_schema: TestInput.v1
output_schema: string
allowed_for_agents:
  - marketing
fallback: null
cache_policy:
  enabled: true
  ttl_seconds: 60
""",
        encoding="utf-8",
    )
    call_count = 0

    def handler(request: httpx.Request) -> httpx.Response:
        nonlocal call_count
        call_count += 1
        return httpx.Response(
            200,
            json={
                "choices": [{"message": {"content": f"proxy-call-{call_count}"}}],
                "usage": {"total_tokens": 10},
            },
        )

    gateway = LLMGateway(
        prompt_registry=PromptRegistry(prompt_dir),
        http_client=httpx.Client(transport=httpx.MockTransport(handler)),
        cache=InMemoryLLMCache(),
    )

    first = gateway.generate_text(
        prompt_id="cached_prompt_v1",
        agent="marketing",
        input_data={"sku": "SKU-1003"},
    )
    second = gateway.generate_text(
        prompt_id="cached_prompt_v1",
        agent="marketing",
        input_data={"sku": "SKU-1003"},
    )

    assert first.output == "proxy-call-1"
    assert first.cached is False
    assert second.output == "proxy-call-1"
    assert second.cached is True
    assert call_count == 1


def test_llm_gateway_bypasses_cache_when_policy_disables_it(tmp_path):
    prompt_dir = tmp_path / "prompts"
    prompt_dir.mkdir()
    (prompt_dir / "uncached_prompt.yaml").write_text(
        """
prompt_id: uncached_prompt_v1
agent: marketing
provider: litellm
model: openai/gpt-4.1-mini
system_prompt: Generate uncached copy.
temperature: 0.0
max_tokens: 50
input_schema: TestInput.v1
output_schema: string
allowed_for_agents:
  - marketing
fallback: null
cache_policy:
  enabled: false
""",
        encoding="utf-8",
    )
    call_count = 0

    def handler(request: httpx.Request) -> httpx.Response:
        nonlocal call_count
        call_count += 1
        return httpx.Response(
            200,
            json={"choices": [{"message": {"content": f"proxy-call-{call_count}"}}]},
        )

    gateway = LLMGateway(
        prompt_registry=PromptRegistry(prompt_dir),
        http_client=httpx.Client(transport=httpx.MockTransport(handler)),
        cache=InMemoryLLMCache(),
    )

    first = gateway.generate_text("uncached_prompt_v1", "marketing", {"sku": "SKU-1003"})
    second = gateway.generate_text("uncached_prompt_v1", "marketing", {"sku": "SKU-1003"})

    assert first.output == "proxy-call-1"
    assert second.output == "proxy-call-2"
    assert first.cached is False
    assert second.cached is False
    assert call_count == 2


def test_in_memory_llm_cache_expires_entries():
    cache = InMemoryLLMCache()
    response = LLMGateway().generate_text(
        prompt_id="marketing_draft_v1",
        agent="marketing",
        input_data={"product_name": "Trail Runner", "offer": "10% off"},
    )

    cache.set("cache-key", response, ttl_seconds=0)
    time.sleep(0.001)

    assert cache.get("cache-key") is None
